spring.application.name=Product_Management_System

spring.datasource.url=jdbc:postgresql://localhost:5432/Product_Management
spring.datasource.username=postgres
spring.datasource.password=Revanth@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
